# Generated by Django 4.0.4 on 2022-06-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_company', to='main.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_company', to='main.company'),
        ),
    ]
